# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sBPhLbbcGC_d5IGQqfSX1l4nXL-AxUB
"""

import pandas as pd
baza={
    "FISH":[  "Muhammadkarim Akbaraliyev ","Nazirov Jasurbek","Zaripov Xabibullo" ,"Ibrohimov Ozodbek","Sultanov Fazliddin","ASQARALIYEV ASLIDDIN","NABIYEV IBROXIM","Mirzayev Ibrohim"],
    "Manzili":[ "Farg'ona tumani","Farg'ona tumani","Farg'ona tumani","Farg'ona tumani","Namangan shahar","Farg‘ona viloyati","Quva tumani","Beshariq tumani" ],
    "Yoshi":[ "19" ,"19","20","19","19", "21","25","40"],
    "Ish joyi":[ "TATUFF","TATUFF","TATUFF","TATUFF","TATUFF","TATUFF","FNQIZ","Obodonlashtirish" ],
    "Jinsi":[ "Erkak","Erkak","Erkak","Erkak","Erkak","Erkak","Erkak","Erkak" ]

}
db=pd.DataFrame(baza)
print(db)

filtr=db[(db['Yoshi']>="20") & (db["Ish joyi"]=="TATUFF")]

print(filtr)

filtr=db[db['Ish joyi']=="TATUFF"]
print(filtr)

filtr=db[db['Manzili']>="Farg'ona tumani"]
print(filtr)